In [1]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
%matplotlib inline
import math

In [2]:
diet=pd.read_csv('dietstudy.csv')
diet.head(16)

patid  age  gender  tg0  tg1  tg2  tg3  tg4  wgt0  wgt1  wgt2  wgt3  wgt4
0       1   45    Male  180  148  106  113  100   198   196   193   188   192
1       2   56    Male  139   94  119   75   92   237   233   232   228   225
2       3   50    Male  152  185   86  149  118   233   231   229   228   226
3       4   46  Female  112  145  136  149   82   179   181   177   174   172
4       5   64    Male  156  104  157   79   97   219   217   215   213   214
5       6   49  Female  167  138   88  107  171   169   166   165   162   161
6       7   63    Male  138  132  146  143  132   222   219   215   215   210
7       8   63  Female  160  128  150  118  123   167   167   166   162   161
8       9   52    Male  107  120  129  195  174   199   200   196   196   193
9      10   45    Male  156  103  126  135   92   233   229   229   229   226
10     11   61  Female   94  144  114  114  121   179   181   176   173   173
11     12   49  Female  107   93  156  148  150   158   153   155   155   154
12     13   61  Female  145  107  129   86  159   157   151   150   145   143
13     14   59    Male  186  142  128  122  101   216   213   210   210   206
14     15   52    Male  112  107  103   89  148   257   255   254   252   249
15     16   60  Female  104  103  117   79  130   151   146   144   144   140

## 1. A physician is evaluating a new diet for her patients with a family history of heart disease. To test the effectiveness of this diet, 16 patients are placed on the diet for 6 months. Their weights and triglyceride levels are measured before and after the study,and the physician wants to know if either set of measurements has changed. (Data set: dietstudy.csv)

In [3]:
#Null Hypothesis:- The weights and triglyceride levels  measured before and after the diet are same

#Paired T-test
#test on triglycerides
stats.ttest_rel(a=diet.tg0,
                b=diet.tg4)

Ttest_relResult(statistic=1.2000008533342437, pvalue=0.24874946576903698)

In [4]:
# p value > 0.05, we are unable to reject null hypothesis, hence, we can say 
#triglyceride levels  measured before and after the diet are same

#2 sample Paired T-test on weight
stats.ttest_rel(a=diet.wgt0,
                b=diet.wgt4)
# p value < 0.05 and +ve statistic depicts a>b, we are able to reject null hypothesis, hence, we can say 
#weight levels  measured before the diet were more.

Ttest_relResult(statistic=11.174521688532522, pvalue=1.137689414996614e-08)

## 2. An analyst at a department store wants to evaluate a recent credit card promotion. To this end, 500 cardholders were randomly selected. Half received an ad promoting a reduced interest rate on purchases made over the next three months, and half received a standard seasonal ad. Is the promotion effective to increase sales? (Data set: creditpromo.csv)

In [5]:
credit=pd.read_csv('creditpromo.csv')
credit.head()

id         insert      dollars
0   148       Standard  2232.771979
1   572  New Promotion  1403.807542
2   973       Standard  2327.092181
3  1096       Standard  1280.030541
4  1541  New Promotion  1513.563200

In [6]:
#Null Hypothesis:- The purchase levels are same for standard and new promotion.

standard = credit[credit['insert']=='Standard'].dollars
new_promotion = credit[credit['insert']=='New Promotion'].dollars

In [7]:
#2 sample independent T-test on weight
stats.ttest_ind(a= standard,
                b= new_promotion,
                equal_var=True)   
#p<0.05, we are able to reject null hypothesis and -ve statistic sign depicts b>a, 
#Hence, we can say promotion was effective in increasing sales

Ttest_indResult(statistic=-2.2604227264649963, pvalue=0.024225996894147814)

## 3. An experiment is conducted to study the hybrid seed production of bottle gourd under open field conditions. The main aim of the investigation is to compare natural pollination and hand pollination. The data are collected on 10 randomly selected plants from each of natural pollination and hand pollination. The data are collected on fruit weight (kg), seed yield/plant (g) and seedling length (cm). (Data set: pollination.csv)a. Is the overall population of Seed yield/plant (g) equals to 200?


In [8]:
#Null Hypothesis:- The overall population of Seed yield/plant (g) equals to 200

pollination=pd.read_csv('pollination.csv')
pollination.head(20)

Group  Fruit_Wt  Seed_Yield_Plant  Seedling_length
0   Natural      1.85            147.70            16.86
1   Natural      1.86            136.86            16.77
2   Natural      1.83            149.97            16.35
3   Natural      1.89            172.33            18.26
4   Natural      1.80            144.46            17.90
5   Natural      1.88            138.30            16.95
6   Natural      1.89            150.58            18.15
7   Natural      1.79            140.99            18.86
8   Natural      1.85            140.57            18.39
9   Natural      1.84            138.33            18.58
10     Hand      2.58            224.26            18.18
11     Hand      2.74            197.50            18.07
12     Hand      2.58            230.34            19.07
13     Hand      2.62            217.05            19.00
14     Hand      2.68            233.84            18.00
15     Hand      2.56            216.52            18.49
16     Hand      2.34            211.93            17.45
17     Hand      2.67            210.37            18.97
18     Hand      2.45            199.87            19.31
19     Hand      2.44            214.30            19.36

In [9]:
#One Sample T-Test
stats.ttest_1samp(a= pollination.Seed_Yield_Plant,popmean=200)
#p-value<0.05, we are able to reject null hypothesis, -ve statistic sign depicts Seed yield/plant is less than 200 
#hence, we can say overall population of Seed yield/plant (g) not equals to 200.

Ttest_1sampResult(statistic=-2.3009121248548645, pvalue=0.032891040921283025)

## b. Test whether the natural pollination and hand pollination under open field conditions are equally effective or are significantly different.

In [10]:
Hand = pollination[pollination.Group=='Hand']
Natural = pollination[pollination.Group=='Natural']

In [11]:
#Null Hypothesis:- the natural pollination and hand pollination under open field conditions are equally effective

#2 sample independent T-test on  fruit weight
stats.ttest_ind(a= Hand.Fruit_Wt,
                b= Natural.Fruit_Wt,
                equal_var=True)

Ttest_indResult(statistic=17.669989614440286, pvalue=8.078362076486221e-13)

In [12]:
#p<0.05, we are able to reject null hypothesis and -ve statistic sign depicts b>a

#2 sample independent T-test on seed yield/plant
stats.ttest_ind(a= Hand.Seed_Yield_Plant,
                b= Natural.Seed_Yield_Plant,
                equal_var=True)

Ttest_indResult(statistic=13.958260515902547, pvalue=4.271481585484385e-11)

In [13]:
#p<0.05, we are able to reject null hypothesis and +ve statistic sign depicts a>b

#2 sample independent T-test on seedling lenght
stats.ttest_ind(a= Hand.Seedling_length,
                b= Natural.Seedling_length,
                equal_var=True)

#p<0.05, we are able to reject null hypothesis and +ve statistic sign depicts a>b
#Hence, all three tests are able to reject null hypothesis, we can say that
#the natural pollination and hand pollination under open field conditions are significantly different

Ttest_indResult(statistic=2.542229999657055, pvalue=0.020428817064110226)

## 4. An electronics firm is developing a new DVD player in response to customer requests.Using a prototype, the marketing team has collected focus data for different age groups viz.Under 25; 25-34; 35-44; 45-54; 55-64; 65 and above. Do you think that consumers of various ages rated the design differently? (Data set: dvdplayer.csv).

In [14]:
dvd=pd.read_csv('dvdplayer.csv')
dvd.head()

agegroup   dvdscore
0  65 and over  38.454803
1        55-64  17.669677
2  65 and over  31.704307
3  65 and over  25.924460
4     Under 25  30.450007

In [15]:
#Null Hypothesis:- consumers of various ages rated the design similarly

s1 = dvd.dvdscore[dvd.agegroup=='Under 25']
s2 = dvd.dvdscore[dvd.agegroup=='25-34']
s3 = dvd.dvdscore[dvd.agegroup=='35-44']
s4 = dvd.dvdscore[dvd.agegroup=='45-54']
s5 = dvd.dvdscore[dvd.agegroup=='65 and over']

In [16]:
#ANOVA test

stats.f_oneway(s1, s2, s3,s4,s5)

F_onewayResult(statistic=8.052067513385818, pvalue=3.22532865708216e-05)

In [17]:
#p<0.05, we are able to reject null hypothesis.
#Hence, we can say consumers of various ages rated the design differently.

## 5. A survey was conducted among 2800 customers on several demographic characteristics. Working status, sex, age, age-group, race, happiness, no. of child, marital status, educational qualifications, income group etc. had been captured for that purpose. (Data set: sample_survey.csv).a. Is there any relationship in between labour force status with marital status?


In [18]:
survey=pd.read_csv('sample_survey.csv')
survey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2832 entries, 0 to 2831
Data columns (total 46 columns):
id          2832 non-null int64
wrkstat     2831 non-null object
marital     2831 non-null object
childs      2825 non-null float64
age         2828 non-null float64
educ        2820 non-null float64
paeduc      2041 non-null float64
maeduc      2399 non-null float64
speduc      1311 non-null float64
degree      2822 non-null object
sex         2832 non-null object
race        2832 non-null object
born        2819 non-null object
parborn     2812 non-null object
granborn    2630 non-null float64
income      2503 non-null object
rincome     1849 non-null object
polviews    2691 non-null object
cappun      2599 non-null object
postlife    2066 non-null object
happy       2806 non-null object
hapmar      1337 non-null object
owngun      1869 non-null object
news        1870 non-null object
tvhours     2337 non-null float64
howpaid     1347 non-null object
ethnic      2238 non-null ob

In [20]:
#Null Hypothesis:- there is no  relationship in between labour force status with marital status

#chi-square test
t1=pd.crosstab(survey.wrkstat, survey.marital, margins = True)
print(t1)
stats.chi2_contingency(observed= t1)

marital                  Divorced  Married  Never married  Separated  Widowed  \
wrkstat                                                                         
Keeping house                  25      200             35         13       55   
Other                          12       16             14          4        8   
Retired                        53      168             17          6      150   
School                          7        9             60          2        1   
Temporarily not working         9       23             11          1        2   
Unemployed, laid off           10       13             32          0        3   
Working full time             295      778            392         58       44   
Working part-time              35      138            102          9       20   
All                           446     1345            663         93      283   

marital                   All  
wrkstat                        
Keeping house             328  
Other       

(729.2421426572284,
 1.820339965538765e-127,
 40,
 array([[5.16918728e+01, 1.55886926e+02, 7.68424028e+01, 1.07787986e+01,
         3.28000000e+01, 3.28000000e+02],
        [8.51024735e+00, 2.56643110e+01, 1.26508834e+01, 1.77455830e+00,
         5.40000000e+00, 5.40000000e+01],
        [6.20932862e+01, 1.87254417e+02, 9.23045936e+01, 1.29477032e+01,
         3.94000000e+01, 3.94000000e+02],
        [1.24501767e+01, 3.75459364e+01, 1.85077739e+01, 2.59611307e+00,
         7.90000000e+00, 7.90000000e+01],
        [7.24946996e+00, 2.18621908e+01, 1.07766784e+01, 1.51166078e+00,
         4.60000000e+00, 4.60000000e+01],
        [9.14063604e+00, 2.75653710e+01, 1.35879859e+01, 1.90600707e+00,
         5.80000000e+00, 5.80000000e+01],
        [2.46954770e+02, 7.44740283e+02, 3.67109894e+02, 5.14950530e+01,
         1.56700000e+02, 1.56700000e+03],
        [4.79095406e+01, 1.44480565e+02, 7.12197880e+01, 9.99010601e+00,
         3.04000000e+01, 3.04000000e+02],
        [4.46000000e+02, 1.345

In [ ]:
# As p<0.05, we are able to reject the null hypothesis
#Hence, we can say there is relationship between labour force status with marital status.

## b. Do you think educational qualification is somehow controlling the marital status?


In [21]:
#Null Hypothesis:- there is no  relationship in between educational qualification with marital status

#chi-square test
t2=pd.crosstab(survey.degree, survey.marital, margins = True)
print(t2)
stats.chi2_contingency(observed= t2)

marital         Divorced  Married  Never married  Separated  Widowed   All
degree                                                                    
Bachelor              58      251            129         12       28   478
Graduate              29      123             41          3        9   205
High school          241      686            367         58      148  1500
Junior college        45      108             46          3        6   208
LT High school        70      174             77         17       92   430
All                  443     1342            660         93      283  2821


(122.68449020508541,
 7.424404099753273e-15,
 25,
 array([[  75.06345268,  227.39312301,  111.83268345,   15.75824176,
           47.95249911,  478.        ],
        [  32.19248493,   97.52215526,   47.9617157 ,    6.75824176,
           20.56540234,  205.        ],
        [ 235.55476781,  713.57674583,  350.9393832 ,   49.45054945,
          150.4785537 , 1500.        ],
        [  32.66359447,   98.94930876,   48.66359447,    6.85714286,
           20.86635945,  208.        ],
        [  67.52570011,  204.55866714,  100.60262318,   14.17582418,
           43.1371854 ,  430.        ],
        [ 443.        , 1342.        ,  660.        ,   93.        ,
          283.        , 2821.        ]]))

In [ ]:
# As p<0.05, we are able to reject the null hypothesis
#Hence, we can say there is relationship between educational qualification with marital status.

## c. Is happiness is driven by earnings or marital status?

In [22]:
#Null Hypothesis:- there is no  relationship in between happiness and marital status

#chi-square test
t3=pd.crosstab(survey.happy, survey.marital, margins = True)
print(t3)
stats.chi2_contingency(observed= t3)


marital        Divorced  Married  Never married  Separated  Widowed   All
happy                                                                    
Not too happy        72       71            108         30       59   340
Pretty happy        278      684            426         49      137  1574
Very happy           93      582            120         13       83   891
All                 443     1337            654         92      279  2805


(260.68943894182826,
 7.762777322980048e-47,
 15,
 array([[  53.6969697 ,  162.06060606,   79.27272727,   11.15151515,
           33.81818182,  340.        ],
        [ 248.58538324,  750.24527629,  366.98609626,   51.62495544,
          156.55828877, 1574.        ],
        [ 140.71764706,  424.69411765,  207.74117647,   29.22352941,
           88.62352941,  891.        ],
        [ 443.        , 1337.        ,  654.        ,   92.        ,
          279.        , 2805.        ]]))

In [23]:
# As p<0.05, we are able to reject the null hypothesis
#Hence,we can say happiness is driven by marital status.

In [24]:
#Null Hypothesis:- there is no  relationship in between happiness and earnings

#chi-square test
t3a=pd.crosstab(survey.happy, survey.income, margins = True)
print(t3a)
stats.chi2_contingency(observed= t3a)

income         $1000 TO 2999  $10000 - 14999  $15000 - 19999  $20000 - 24999  \
happy                                                                          
Not too happy              7              39              33              40   
Pretty happy              20             107             119             155   
Very happy                 5              44              26              50   
All                       32             190             178             245   

income         $25000 or more  $3000 TO 3999  $4000 TO 4999  $5000 TO 5999  \
happy                                                                        
Not too happy             113              9              9              6   
Pretty happy              888             11             13             18   
Very happy                571              4             10             11   
All                      1572             24             32             35   

income         $6000 TO 6999  $7000 TO 7999  $8000

(178.95053061216427,
 7.234749067043371e-21,
 36,
 array([[   3.89520355,   23.12777106,   21.66706973,   29.82265216,
          191.35187424,    2.92140266,    3.89520355,    4.26037888,
            4.01692866,    5.72108021,    7.06005643,    4.26037888,
          302.        ],
        [  18.16041919,  107.82748892,  101.01733172,  139.04070939,
          892.1305925 ,   13.62031439,   18.16041919,   19.86295848,
           18.72793229,   26.67311568,   32.91575977,   19.86295848,
         1408.        ],
        [   9.94437727,   59.04474002,   55.31559855,   76.13663845,
          488.51753325,    7.45828295,    9.94437727,   10.87666264,
           10.25513906,   14.60580411,   18.0241838 ,   10.87666264,
          771.        ],
        [  32.        ,  190.        ,  178.        ,  245.        ,
         1572.        ,   24.        ,   32.        ,   35.        ,
           33.        ,   47.        ,   58.        ,   35.        ,
         2481.        ]]))

In [ ]:
# As p<0.05, we are able to reject the null hypothesis
#Hence,we can say happiness is driven by earnings.